### PR TITLE
Fix Godot 4.0 compile errors, update JavaScript integration, refactor code, and address minor issues

### PR DESCRIPTION
**Pull request by fire**
To review the changes on top of gd4.

This is blocked on the build process with mvsc.

### CODE REVIEW

**Comment by Geequlim** [comment]
It's ok to keep master to compatiable with godot master branch.
It should be better to rename current master branch to 3.x for someone who need that and mention it in readme.
@fire Can you help make a new branch for 3.x and update the readme in this pr ?

**Comment by fire** [comment]
Since I'm not able to work on this imediately.

Here's the plan:

1. Create a `3.x` branch.
2. Add phrasing to the README. Need some help on this.

**Comment by fire** [comment]
The current errors don't make sense:

```bash

scons: *** [thirdparty/glslang/glslang/MachineIndependent/attribute.windows.editor.x86_64.o] Error 1
In file included from thirdparty/glslang/glslang/MachineIndependent/ParseHelper.h:53,
                 from thirdparty/glslang/glslang/MachineIndependent/attribute.cpp:41:
thirdparty/glslang/glslang/MachineIndependent/SymbolTable.h:648:18: error: 'uint32_t' does not name a type
  648 |     static const uint32_t LevelFlagBitOffset = 56;
      |               ```

**Comment by system32uwu** [comment]
Sounds related to this: https://github.com/godotengine/godot/pull/77949

I get the same error locally if I try to build it using MSYS2 MinGW

**Comment by fire** [comment]
It builds when I copy the module into git godot engine https://github.com/V-Sekai/godot/tree/vsk-javascript.

Note that only linux and windows platforms are set to build.

**Comment by fire** [comment]
I have no idea how to fix this.

**Comment by tekenik** [comment]
Siema i dzięki

**Review by tekenik — APPROVED** [review]

**Comment by jaune** [comment]
@fire anynews / progress?

**Comment by fire** [comment]
I am stuck compiling for Windows on MSVC.

**Comment by jaune** [comment]
QuickJs is not really compatible with MSVC.

I made some changes to make it compile, but it crash.

I will investigate tomorrow, and post my changes if working.

**Comment by jaune** [comment]
@fire it compile and "run" => https://github.com/Geequlim/ECMAScript/pull/161

It's really durty, but it's a first step.

**Comment by jaune** [comment]
@fire Can I delete https://github.com/Geequlim/ECMAScript/pull/161? I will have some time next week, I can try to make the CI pass for Windows.

What version for Godot this PR should work with?

**Comment by fire** [comment]
I am targeting master because of graph node changes.

**Comment by fire** [comment]
@jaune if you wish you can close it.

**Comment by jaune** [comment]
> I am targeting master because of graph node changes.

CI uses the last commit on branch `4.0` and not `master` because of `GODOT_BASE_BRANCH: '4.0'` in workflows.

PR https://github.com/Geequlim/ECMAScript/pull/162 should fix the CI, I can not run the CI to make sure of it.

**Pull request merged**
