### PR TITLE
Adding doc generation using typedoc.

### PR DESCRIPTION
**Pull request by Flux159**
This pull request adds a script in misc/package.json in order to generate docs into a misc/docs folder.

Run the following to create a docs folder:

```
cd misc
yarn
yarn generatedocs
```

The folder itself is gitignored, in order to generate Github Pages hosted documentation, you want to create a new **empty** `gh-pages` branch, move the docs folder into the root of that branch, then update a few configuration files for github pages (specifically a `.nojekyll` file and adding a `_config.yml` in the gh-pages branch like https://github.com/Flux159/ECMAScript/commits/gh-pages)

The reason I didn't move this into the Github action to automate is because it requires work from the repository owner to setup push permissions via Github Actions, so this is just a manual way of generating docs for now.

### CODE REVIEW

**Comment by Flux159** [comment]
References #65

**Comment by Geequlim** [comment]
Is misc/yarn.lock is required?

**Comment by Flux159** [comment]
> Is misc/yarn.lock is required?

Technically it should be committed to have more deterministic package installs. I don't think it matters too much in this case, but it's fairly standard to know if deps end up changing.

**Comment by fire** [comment]
@Geequlim Thoughts about closing this since it has not been updated in 3 years?

If there's any interest, I think the proposal is still doable.

**Comment by fire** [comment]
Closing to to lack of response.

**Pull request closed without merging**
