### PR TITLE
Godot 4 Builds via Github Actions

### PR DESCRIPTION
**Pull request by animanmaster**
These changes managed to get me working Godot 4 + Ecmascript builds via Github Actions. I've only done light testing with the Windows editor build and my own project, so definitely needs more testing to make sure everything works as expected, and there's more cleanup work that should be done to the Github Actions, but I figured I'd make this PR in case it helps/inspires others to take it further. :)

### CODE REVIEW

**Comment by animanmaster** [comment]
Also just now realized there's a script that generates the Github Actions from the main repo 🤦 Probably would've saved a few commits if I just read the README fully 🙃 Will try that out to see if gives a cleaner result than the manual edits I did here. 🤞

**Comment by Geequlim** [comment]
Good work!
Can you git squash commits ?

**Comment by fire** [comment]
@animanmaster Are you able to work on this in the next two weeks?

**Comment by fire** [comment]
Thanks for your work. @Geequlim @animanmaster 

As https://github.com/Geequlim/ECMAScript/pull/150 is merged, this can be closed.

**Comment by fire** [comment]
Thanks!

**Comment by animanmaster** [comment]
Sorry for the delay, thanks for picking this up @fire.

**Pull request closed without merging**
