### PR TITLE
Refactor JavaScript integration and improve code readability.

### PR DESCRIPTION
**Pull request by nmerget**
Hey, I'm not into C++ so I did some try/error to fix the issues for the CI.

- Update `.github/actions`: 
  - Moved the version to another `workflow_call` to reuse it for better maintenance (I going to open up an issue with my suggestions)
  - fixed issue with `linux` builds by removing `werror=yes`, which could be enabled again but [Wno-error="cast-function-type"](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html) didn't work with `SCONSFLAGS` 
  - removed dev_builds for linux because of the debugger
  
- removing/changing issues inside the ci:
  - some issues from this [PR](https://github.com/Geequlim/ECMAScript/pull/162)
  - disabling the debugger for now to make sure the pipeline won't fail

**This branch should be squashed**  👍

### CODE REVIEW

**Comment by fire** [comment]
I approved the github actions. Been busy so if someone can continue the work on https://github.com/Geequlim/ECMAScript/pull/156 that'll be amazing.

**Comment by fire** [comment]
I think the js debugger is still being used so the build complains about needing it.

**Comment by nmerget** [comment]
@fire the pipeline is running now

The first run takes very long especially for `windows`, I don't know if this is a normal behavior when building the editor. After the cache is initialized it is way faster.

**Please squash this branch before merging, I added a lot of testing commits because of the pipeline, we don't need them in the history**

I propose merging the open PRs to have a working `4.1` branch.
Afterward, I would like to structure the repo differently and add some extra workflow_calls to publish the artifacts: https://github.com/Geequlim/ECMAScript/issues/165

**Comment by fire** [comment]
Can you squash? I want to keep attribution intact

**Comment by fire** [comment]
Thanks

**Pull request merged**
